name: Pull Request for Release

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    permissions:
      contents: read
      pull-requests: write
    env:
      VERSION: ${{ github.ref_name#release/ }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version
        run: echo "version=${{ github.ref_name#release/ }}" >> $GITHUB_ENV

      - name: Add label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label release -t ${{ version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  size-check:
    runs-on: ubuntu-latest
    needs: label
    permissions:
      pull-requests: write
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
